# Do not change this (Only for internal use)!
config-version: 1.2

# Messages Configuration
# These messages are used when muting player chats.
# You can use "ยง" or "&" to color the messages.

# The message displayed to players when they attempt to chat during global mute.
message: "&cYou can't chat when global mute is enabled"

# The message displayed to players when the global mute is turned on.
turn-on: "&aMute chat for all players has been turned on"

# The message displayed to players when the global mute is turned off.
turn-off: "&aMute chat for all players has been turned off"
