---
# Do not change this (Only for internal use)!
config-version: 1

# Messages are used when muting player chats.
# Use "ยง" or "&" to color the message.
message: "&cYou can't chat when global mute is enabled"
...